'use client';
import {useState} from 'react';
import {Mountain,Flag,Plus,Pencil,Trash2,Check,ArrowUp,ArrowDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {goalProgress,newGoalStep,moveGoalStep,type Goal} from '@/lib/goals';

function GoalMountain({goal,busy,onToggle}:{goal:Goal;busy:boolean;onToggle:(goal:Goal,id:string,done:boolean)=>void}){
 const height=Math.max(400,goal.steps.length*62+140),base=height-45,top=100;
 const points=goal.steps.map((step,i)=>{const t=(i+1)/goal.steps.length;return {step,x:320+(i%2===0?-1:1)*(1-t)*180,y:base-(base-top)*t};});
 const status=goalProgress(goal);
 return <div className="goal-mountain"><div className="goal-summit"><Flag size={19}/><strong>{status.complete?'Sommet atteint !':'Mon sommet'}</strong></div><svg viewBox={`0 0 640 ${height}`} role="group" aria-label={`Montagne de l’objectif : ${goal.title}. ${status.done} étapes réalisées sur ${status.total}. Les numéros correspondent à la liste.`}>
 <path d={`M 10 ${base+20} L 190 ${height*.4} L 305 ${base+20} Z`} fill="#dce7db"/>
 <path d={`M 370 ${base+20} L 495 ${height*.36} L 630 ${base+20} Z`} fill="#e2e9dd"/>
 <path d={`M 65 ${base+20} L 320 57 L 575 ${base+20} Z`} fill="#abc2a7"/>
 <path d={`M 320 57 L 575 ${base+20} L 320 ${base+20} Z`} fill="#92af94"/>
 <path d={`M 320 57 L ${320-255*80/(base-37)} 137 L 310 118 L 335 135 L ${320+255*80/(base-37)} 137 Z`} fill="#fffdf5"/>
 <path d={`M 320 57 V 21 L 361 32 L 320 42`} fill={status.complete?'#b78232':'#507b53'} stroke="#355d3c" strokeWidth="3" strokeLinejoin="round"/>
 <path d={`M 320 ${base} ${points.map(p=>`L ${p.x} ${p.y}`).join(' ')}`} fill="none" stroke="#fffdf5" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round"/>
 <path d={`M 320 ${base} ${points.map(p=>`L ${p.x} ${p.y}`).join(' ')}`} fill="none" stroke="#698969" strokeWidth="2" strokeDasharray="4 8"/>
 {points.map(({step,x,y},i)=><g key={step.id} className="goal-marker" role="button" tabIndex={busy?-1:0} aria-disabled={busy} aria-pressed={step.done} aria-label={`Étape ${i+1} : ${step.title}, ${step.done?'réalisée':'à faire'}. ${step.done?'Décocher':'Cocher'}`} onClick={()=>{if(!busy)onToggle(goal,step.id,!step.done)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!busy)onToggle(goal,step.id,!step.done)}}}><circle cx={x} cy={y} r="23" fill={step.done?'#355e40':'#fffdf5'} stroke={status.next?.id===step.id?'#b78132':'#547858'} strokeWidth={status.next?.id===step.id?4:2}/><text x={x} y={y+6} textAnchor="middle" fill={step.done?'#fff':'#355e40'} fontSize="18" fontWeight="700" aria-hidden="true">{step.done?'✓':i+1}</text></g>)}
 <text x="320" y={height-12} textAnchor="middle" fill="#527054" fontSize="17">Le départ</text>
 </svg><p>Chaque repère correspond à une étape ci-dessous.</p></div>;
}
export function GoalsSection({goals,draft,onDraft,onCreate,onSave,onToggle,onDelete,onClose,busy}:{goals:Goal[];draft:Goal|null;onDraft:(v:Goal)=>void;onCreate:()=>void;onSave:()=>void;onToggle:(goal:Goal,id:string,done:boolean)=>void;onDelete:(goal:Goal)=>void;onClose:()=>void;busy:boolean}){
 const [selected,setSelected]=useState<string|null>(null);
 const active=goals.find(g=>g.id===selected)||goals[0];
 const progress=active?goalProgress(active):null;
 return <div className="page-content goals-page"><div className="section-heading goals-heading"><div><span className="eyebrow">UN SOMMET À LA FOIS</span><h2>Mes objectifs</h2></div><Button disabled={busy} onClick={onCreate}><Plus size={17}/> Nouvel objectif</Button></div>
 {!goals.length?<div className="card goal-empty"><Mountain size={64} strokeWidth={1.3}/><h3>Quel sommet veux-tu atteindre ?</h3><p>Choisis un objectif, découpe-le en petites étapes et vois ton chemin se dessiner.</p><Button disabled={busy} variant="outline" onClick={onCreate}>Créer mon premier objectif</Button></div>:<><div className="goal-switcher" aria-label="Choisir un objectif">{goals.map(goal=>{const p=goalProgress(goal);return <button key={goal.id} className={active?.id===goal.id?'selected':''} aria-pressed={active?.id===goal.id} onClick={()=>setSelected(goal.id)}><Mountain size={21}/><span>{goal.title}<small>{p.complete?'Atteint':`${p.done}/${p.total} étapes`} · {p.percent} %</small></span></button>})}</div>
 {active&&progress&&<article className="card goal-detail"><div className="section-heading goals-heading"><div><h3>{active.title}</h3>{active.details&&<p className="goal-details">{active.details}</p>}</div><div className="goal-tools"><Button variant="outline" size="sm" disabled={busy} onClick={()=>onDraft(structuredClone(active))}><Pencil size={15}/> Modifier</Button><Button variant="ghost" size="icon" disabled={busy} aria-label={`Supprimer l’objectif ${active.title}`} onClick={()=>onDelete(active)}><Trash2 size={17}/></Button></div></div><div className="goal-progress" aria-live="polite"><strong>{progress.complete?'Bravo, toutes les étapes sont réalisées !':`${progress.done} étape${progress.done>1?'s':''} sur ${progress.total}`}</strong><span>{progress.percent} %</span><progress max={progress.total} value={progress.done} aria-label="Progression de l’objectif"/></div><div className="goal-journey"><GoalMountain goal={active} busy={busy} onToggle={onToggle}/><div className="goal-route"><h4>Mon chemin vers le sommet</h4><p>Tu peux cocher les étapes à ton rythme, dans l’ordre qui te convient.</p><ol>{active.steps.map((step,i)=><li key={step.id} className={`${step.done?'done':''} ${progress.next?.id===step.id?'next':''}`}><span className="goal-step-number" aria-hidden="true">{i+1}</span><label><Checkbox checked={step.done} disabled={busy} onCheckedChange={v=>onToggle(active,step.id,v===true)} aria-label={`Étape ${i+1} : ${step.title}`}/><span>{step.title}{progress.next?.id===step.id&&<small>Prochaine étape</small>}</span></label></li>)}</ol><p className="goals-hint">Cocher ou décocher une étape enregistre ta progression.</p></div></div></article>}</>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="editor-dialog goal-dialog"><DialogHeader><DialogTitle>{goals.some(g=>g.id===draft?.id)?'Modifier mon objectif':'Un nouvel objectif'}</DialogTitle><DialogDescription>Définis ton sommet et les étapes pour y parvenir.</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();onSave()}}><fieldset className="form-stack goal-fields" disabled={busy}><label>Mon objectif<Input autoFocus required maxLength={150} value={draft.title} placeholder="Ex. Trouver un travail qui me correspond" onChange={e=>onDraft({...draft,title:e.target.value})}/></label><label>Ce qui me motive (facultatif)<Textarea maxLength={2000} value={draft.details} onChange={e=>onDraft({...draft,details:e.target.value})} placeholder="Pourquoi cet objectif compte pour moi…"/></label><div><h3>Mes étapes · {draft.steps.length}/20</h3><p className="goals-hint">De la première action jusqu’au sommet. Utilise les flèches pour changer l’ordre.</p></div><div className="goal-step-editor">{draft.steps.map((step,i)=><div className="goal-edit-step" key={step.id}><label><span>Étape {i+1}{step.done?' · réalisée':''}</span><Input required maxLength={150} value={step.title} placeholder="Une étape concrète" onChange={e=>onDraft({...draft,steps:draft.steps.map(s=>s.id===step.id?{...s,title:e.target.value}:s)})}/></label><div><Button type="button" variant="ghost" size="icon" disabled={i===0} aria-label={`Monter l’étape ${i+1}`} onClick={()=>onDraft(moveGoalStep(draft,step.id,-1))}><ArrowUp size={16}/></Button><Button type="button" variant="ghost" size="icon" disabled={i===draft.steps.length-1} aria-label={`Descendre l’étape ${i+1}`} onClick={()=>onDraft(moveGoalStep(draft,step.id,1))}><ArrowDown size={16}/></Button><Button type="button" variant="ghost" size="icon" disabled={draft.steps.length<=1} aria-label={`Retirer l’étape ${i+1}`} onClick={()=>onDraft({...draft,steps:draft.steps.filter(s=>s.id!==step.id)})}><Trash2 size={16}/></Button></div></div>)}</div><Button type="button" variant="outline" disabled={draft.steps.length>=20} onClick={()=>onDraft({...draft,steps:[...draft.steps,newGoalStep()]})}><Plus size={16}/> Ajouter une étape</Button><Button type="submit"><Check size={17}/> Enregistrer mon objectif</Button></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
