'use client';
import {useState} from 'react';
import {Target,Lightbulb,BookOpen,Phone,Mail,BriefcaseBusiness,Heart,Dumbbell,Coffee,Users,CalendarDays,House,ListChecks,Plus,Pencil,Trash2,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {taskIcons,type TaskIcon,type PersonalTask} from '@/lib/tasks';

const icons={target:{Icon:Target,label:'Objectif',color:'#487646',background:'#e9f0df'},idea:{Icon:Lightbulb,label:'Créer',color:'#a57623',background:'#fff1cf'},book:{Icon:BookOpen,label:'Apprendre',color:'#4d79a3',background:'#e7f0f8'},phone:{Icon:Phone,label:'Appeler',color:'#578364',background:'#e5f1e6'},mail:{Icon:Mail,label:'Écrire',color:'#8c67a1',background:'#f0e7f5'},work:{Icon:BriefcaseBusiness,label:'Travail',color:'#547c87',background:'#e5eff0'},health:{Icon:Heart,label:'Bien-être',color:'#af6878',background:'#f9e7ed'},sport:{Icon:Dumbbell,label:'Sport',color:'#b47743',background:'#faebdf'},rest:{Icon:Coffee,label:'Pause',color:'#917255',background:'#f3ece1'},people:{Icon:Users,label:'Rencontrer',color:'#7b71a6',background:'#ece9f7'},calendar:{Icon:CalendarDays,label:'Organiser',color:'#547f8d',background:'#e7f2f3'},home:{Icon:House,label:'Quotidien',color:'#a58340',background:'#f5eedb'}};
function TaskSymbol({icon}:{icon:TaskIcon}){const {Icon,color,background}=icons[icon]||icons.target;return <span className="task-symbol" style={{color,background}}><Icon size={25} strokeWidth={1.8}/></span>}
export function TasksSection({tasks,draft,onDraft,onCreate,onSave,onToggle,onDelete,onClose,busy}:{tasks:PersonalTask[];draft:PersonalTask|null;onDraft:(task:PersonalTask)=>void;onCreate:()=>void;onSave:()=>void;onToggle:(task:PersonalTask,done:boolean)=>void;onDelete:(task:PersonalTask)=>void;onClose:()=>void;busy:boolean}) {
 const [filter,setFilter]=useState('todo');
 const done=tasks.filter(t=>t.done).length;
 const visible=tasks.filter(t=>filter==='all'||(filter==='done'?t.done:!t.done)).sort((a,b)=>Number(a.done)-Number(b.done)||b.updated_at.localeCompare(a.updated_at));
 return <div className="page-content tasks-page">
  <div className="section-heading tasks-heading"><div><span className="eyebrow">UN PAS APRÈS L’AUTRE</span><h2>Mes actions à réaliser</h2></div><Button disabled={busy} onClick={onCreate}><Plus size={17}/> Nouvelle action</Button></div>
  <div className="card tasks-overview"><span className="task-symbol"><ListChecks size={26}/></span><div><strong>{tasks.length?`${tasks.length-done} action${tasks.length-done>1?'s':''} à réaliser`:'Ta première action commence ici.'}</strong><p>{done} sur {tasks.length} réalisée{done>1?'s':''}</p><progress max={Math.max(tasks.length,1)} value={done} aria-label={`${done} actions réalisées sur ${tasks.length}`}/></div></div>
  <Tabs value={filter} onValueChange={setFilter}><TabsList className="category-tabs task-filters" aria-label="Filtrer mes actions"><TabsTrigger value="todo">À faire ({tasks.length-done})</TabsTrigger><TabsTrigger value="done">Réalisées ({done})</TabsTrigger><TabsTrigger value="all">Toutes ({tasks.length})</TabsTrigger></TabsList></Tabs>
  <div className="task-list">{visible.map(task=><article className={`card task-card ${task.done?'task-completed':''}`} key={task.id}><label className="task-check"><Checkbox checked={task.done} disabled={busy} aria-label={`${task.done?'Remettre à faire':'Marquer comme réalisée'} : ${task.title}`} onCheckedChange={checked=>onToggle(task,checked===true)}/></label><button className="task-open" onClick={()=>onDraft({...task})} disabled={busy} aria-label={`Modifier l’action ${task.title}`}><TaskSymbol icon={task.icon}/><div><h3>{task.title}</h3>{task.details&&<p>{task.details}</p>}<span className="task-status">{task.done?'Réalisée':'À faire'} · {icons[task.icon]?.label||'Objectif'}</span></div></button><div className="task-card-tools"><Button variant="ghost" size="icon" disabled={busy} aria-label={`Modifier ${task.title}`} onClick={()=>onDraft({...task})}><Pencil size={16}/></Button><Button variant="ghost" size="icon" disabled={busy} aria-label={`Supprimer ${task.title}`} onClick={()=>onDelete(task)}><Trash2 size={16}/></Button></div></article>)}</div>
  {!visible.length&&<div className="empty-state"><ListChecks size={36}/><h2>{filter==='done'?'Chaque petit pas compte.':tasks.length?'Tout est coché !':'Une action, à ton rythme.'}</h2><p>{filter==='done'?'Tes actions cochées apparaîtront ici.':tasks.length?'Tu peux retrouver tes actions dans « Réalisées » ou en ajouter une nouvelle.':'Ajoute une tâche et choisis une icône pour la repérer facilement.'}</p><Button variant="outline" disabled={busy} onClick={onCreate}><Plus size={17}/> Ajouter une action</Button></div>}
  <p className="tasks-hint">Cocher une action enregistre son état. Tu peux la décocher pour la remettre à faire.</p>
  <Dialog open={!!draft} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="editor-dialog task-dialog"><DialogHeader><DialogTitle>{tasks.some(t=>t.id===draft?.id)?'Modifier mon action':'Une nouvelle action'}</DialogTitle><DialogDescription>Un titre clair et une icône pour t’aider à passer à l’action.</DialogDescription></DialogHeader>{draft&&<form className="form-stack" onSubmit={e=>{e.preventDefault();onSave()}}><fieldset disabled={busy} className="task-editor-fields"><label>Mon action<Input autoFocus required maxLength={150} placeholder="Ex. Appeler pour obtenir un rendez-vous" value={draft.title} onChange={e=>onDraft({...draft,title:e.target.value})}/></label><fieldset className="task-icon-field"><legend>Choisir une icône</legend><RadioGroup aria-label="Icône de l’action" value={draft.icon} onValueChange={icon=>onDraft({...draft,icon:icon as TaskIcon})} disabled={busy} className="task-icon-grid">{taskIcons.map(icon=><label key={icon} className={`task-icon-choice ${draft.icon===icon?'selected':''}`}><RadioGroupItem value={icon} aria-label={icons[icon].label}/><TaskSymbol icon={icon}/><span>{icons[icon].label}</span></label>)}</RadioGroup></fieldset><label>Précisions (facultatif)<Textarea maxLength={2000} value={draft.details} onChange={e=>onDraft({...draft,details:e.target.value})} placeholder="Ex. Préparer trois questions avant d’appeler."/></label><Button type="submit" disabled={busy}><Check size={17}/> Enregistrer</Button></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
